apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app-repo
  namespace: askar-karimov
spec:
  interval: 1m0s
  url: <gitlab-app-url>
  secretRef:
    name: app-secret
  ref:
    branch: main
