apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: askar-karimov
spec:
  interval: 1m0s
  url: <gitlab-fluxcd-url>
  ref:
    branch: main
  secretRef:
    name: fluxcd-secret
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: askar-karimov
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./cluster"
  prune: false
